name: Deploy to GitHub Pages
on:
    workflow_dispatch: # Allow manual trigger from GitHub Actions tab
  push:
    branches:
      - main # Set the branch you want to deploy from
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code # Checkout repository
        uses: actions/checkout@v3

      - name: setup node # Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Specify the Node.js version

      - name: install dependencies # Install dependencies
        run: npm install

      - name: build project # Build project
        run: npm run build

      - name: deploy to gh-pages # Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Set the branch you want to deploy to (usually 'gh-pages')
          publish_branch: gh-pages
          # Optional: Set the user name and email for the commit
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          # Optional: Set a custom commit message
          commit_message: "Deploy to GitHub Pages"
